-- MySQL Script generated by MySQL Workbench
-- Sat Nov 28 09:02:21 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema COMP353_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema COMP353_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `COMP353_project` ;
USE `COMP353_project` ;

-- -----------------------------------------------------
-- Table `COMP353_project`.`condo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COMP353_project`.`condo` (
  `condo_id` INT NOT NULL,
  PRIMARY KEY (`condo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COMP353_project`.`storage_space`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COMP353_project`.`storage_space` (
  `ss_id` INT NOT NULL,
  PRIMARY KEY (`ss_id`),
  UNIQUE INDEX `ss_id_UNIQUE` (`ss_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COMP353_project`.`parking_space`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COMP353_project`.`parking_space` (
  `parking_space_id` INT NOT NULL,
  UNIQUE INDEX `parking_space_id_UNIQUE` (`parking_space_id` ASC) VISIBLE,
  PRIMARY KEY (`parking_space_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COMP353_project`.`public_space`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COMP353_project`.`public_space` (
  `square_footage` DOUBLE NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `type_UNIQUE` (`type` ASC) VISIBLE,
  PRIMARY KEY (`square_footage`, `type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COMP353_project`.`Maintenance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COMP353_project`.`Maintenance` (
  `Contractor` VARCHAR(45) NOT NULL,
  `start_date` DATE NOT NULL,
  `Type` VARCHAR(45) NULL,
  `complete_date` DATE NULL,
  `total_cost` DOUBLE NULL,
  PRIMARY KEY (`Contractor`, `start_date`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COMP353_project`.`building`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COMP353_project`.`building` (
  `building_id` INT NOT NULL,
  `square_footage` DOUBLE NOT NULL,
  PRIMARY KEY (`building_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COMP353_project`.`transaction_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COMP353_project`.`transaction_record` (
  `payment_date` DATE NOT NULL,
  `default_monthly_payment` DOUBLE NULL,
  `maintenance_payment` DOUBLE NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COMP353_project`.`condo_owners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COMP353_project`.`condo_owners` (
  `user_id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `percent_owned` DOUBLE NOT NULL,
  `privilege` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


/*row data for building table*/
insert into building values (1, 2300, "3524 Rue Sherbrooke, Montreal, QC");
insert into building values (2, 3000, "1587 Rue Laval, Montreal, QC");
insert into building values (3, 2500, "2490 Rue St Denis, Montreal, QC");

/*row data for condo table*/
insert into condo values (1,1);
insert into condo values (1,2);
insert into condo values (1,3);
insert into condo values (1,4);
insert into condo values (1,5);
insert into condo values (1,6);
insert into condo values (1,7);
insert into condo values (1,8);
insert into condo values (1,9);
insert into condo values (1,10);
insert into condo values (2,1);
insert into condo values (2,2);
insert into condo values (2,3);
insert into condo values (2,4);
insert into condo values (2,5);
insert into condo values (2,6);
insert into condo values (2,7);
insert into condo values (2,8);
insert into condo values (2,9);
insert into condo values (2,10);
insert into condo values (3,1);
insert into condo values (3,2);
insert into condo values (3,3);
insert into condo values (3,4);
insert into condo values (3,5);
insert into condo values (3,6);
insert into condo values (3,7);
insert into condo values (3,8);
insert into condo values (3,9);
insert into condo values (3,10);

/*data for condo_owner table*/
insert into condo_owner values ("shinji_ikari", "s.ikari@hotmail.com", "passw0rd1234", "Shinji Ikari", "3524 Rue Sherbrooke #1, Montreal, QC", "user", 10);
insert into condo_owner values ("misato_katsuragi", "m.katsuragi@gmail.com", "passw0rd1234", "Misato Katsuragi", "3524 Rue Sherbrooke #2, Montreal, QC", "user", 10);
insert into condo_owner values ("rei_ayanami", "r.ayami@yahoo.com", "passw0rd1234", "Rei Ayanami", "3524 Rue Sherbrooke #3, Montreal, QC", "user", 10);
insert into condo_owner values ("asuka_langley_soryu", "a.soryu@hotmail.com", "passw0rd1234", "Asuka Langley Soryu", "3524 Rue Sherbrooke #4, Montreal, QC", "user", 10);
insert into condo_owner values ("gendo_ikari", "g.ikari@gmail.com", "passw0rd1234", "Gendo Ikari", "3524 Rue Sherbrooke #5, Montreal, QC", "admin", 10);
insert into condo_owner values ("ritsuko_akagi", "r.akagi@yahoo.com", "passw0rd1234", "Ritsuko Akagi", "3524 Rue Sherbrooke #6, Montreal, QC", "user", 10);
insert into condo_owner values ("kozo_fuyutsuki", "k.fuyutsuki@hotmail.com", "passw0rd1234", "Kozo Fuyutsuki", "3524 Rue Sherbrooke #7, Montreal, QC", "user", 10);
insert into condo_owner values ("ryoji_kaji", "r.kaji@gmail.com", "passw0rd1234", "Ryoji Kaji", "3524 Rue Sherbrooke #8, Montreal, QC", "user", 10);
insert into condo_owner values ("makoto_hyuga", "m.hyuga@yahoo.com", "passw0rd1234", "Makoto Hyuga", "3524 Rue Sherbrooke #9, Montreal, QC", "user", 10);
insert into condo_owner values ("maya_ibuki", "m.ibuki@hotmail.com", "passw0rd1234", "Maya Ibuki", "3524 Rue Sherbrooke #10, Montreal, QC", "user", 10);
insert into condo_owner values ("shigeru_aoba", "s.aoba@gmail.com", "passw0rd1234", "Shigeru Aoba", "1587 Rue Laval #1, Montreal, QC", "user", 10);
insert into condo_owner values ("kaworu_nagisa", "k.nagisa@yahoo.com", "passw0rd1234", "Kaworu Nagisa", "1587 Rue Laval #2, Montreal, QC", "user", 10);
insert into condo_owner values ("toji_suzuhara", "t.suzuhara@hotmail.com", "passwo0rd1234", "Toji Suzuhara", "1587 Rue Laval #3, Montreal, QC", "user", 10);
insert into condo_owner values ("kensuke_aida", "k.aida@gmail.com", "passw0rd1234", "Kensuke Aida", "1587 Rue Laval #4, Montreal, QC", "user", 10);
insert into condo_owner values ("Hikari Horaki", "h.horaki@yahoo.com", "passw0rd1234", "Hikari Horaki", "1587 Rue Laval #5, Montreal, QC", "user", 10);
insert into condo_owner values ("pen_pen", "p.pen@gmail.com", "passw0rd1234", "Pen Pen", "1587 Rue Laval #6, Montreal, QC", "admin", 10);
insert into condo_owner values ("naoko_akagi", "n.akagi@yahoo.com", "passw0rd1234", "Naoko Akagi", "1587 Rue Laval #7, Montreal, QC", "admin", 10);
insert into condo_owner values ("yui_ikari", "y.ikari@hotmail.com", "passw0rd1234", "Yui Ikari", "1587 Rue Laval #8, Montreal, QC", "user", 10);
insert into condo_owner values ("kyoko_zeppelin_soryu", "k.soryu@gmail.com", "passw0rd1234", "Kyoko Zeppelin Soryu", "1587 Rue Laval #9, Montreal, QC", "user", 10);
insert into condo_owner values ("keel_lorenz", "k.lorenz@yahoo.com", "passw0rd1234", "passw0rd1234", "Keel Lorenz", "1587 Rue Laval #10, Montreal, QC", "user", 10);
insert into condo_owner values ("adam_angel", "a.angel@gmail.com", "Adam Angel", "passw0rd1234", "2490 Rue St Denis #1, Montreal, QC", "admin", 10);
insert into condo_owner values ("lilith_angel", "lth.angel@hotmail.com", "Lilith Angel", "passw0rd1234", "2490 Rue St Denis #2, Montreal, QC", "user", 10);
insert into condo_owner values ("tabris_angel", "t.angel@gmail.com", "Tabris Angel", "passw0rd1234", "2490 Rue St Denis #3, Montreal, QC", "user", 10);
insert into condo_owner values ("lilin_angel", "ln.angel@yahoo.com", "Lilin Angel", "passw0rd1234", "2490 Rue St Denis #4, Montreal, QC", "user", 10);
insert into condo_owner values ("lain_iwakura", "l.iwakura@hotmail.com", "Lain Iwakura", "passw0rd1234", "2490 Rue St Denis #5, Montreal, QC", "user", 10);
insert into condo_owner values ("mika_iwakura", "m.iwakura@gmail.com", "Mika Iwakura", "passw0rd1234", "2490 Rue St Denis #6, Montreal, QC", "user", 10);
insert into condo_owner values ("masami_eiri", "m.eiri@gmail.com", "Masami Eiri", "passw0rd1234", "2490 Rue St Denis #7, Montreal, QC", "user", 10);
insert into condo_owner values ("alice_mizuki", "a.mizuki@yahoo.com", "Alice Mizuki", "passw0rd1234", "2490 Rue St Denis #8, Montreal, QC", "user", 10);
insert into condo_owner values ("chisa_yomoda", "c.yomoda@hotmail.com", "Chisa Yomoda", "passw0rd1234", "2490 Rue St Denis #9, Montreal, QC", "user", 10);
insert into condo_owner values ("yasuo_iwakura", "y.iwakura@gmail.com", "Yasuo Iwakura", "passw0rd1234", "2490 Rue St Denis #10, Montreal, QC", "user", 10);

/*data for maintenance table*/
insert into maintenance values ("Terminexx", 2020-03-24, 2020-03-26, "unclogged rats from sink", 54.10, 1, 7);
insert into maintenance values ("Father Jean Francois", 2020-01-19, 2020-01-19, "excorcized malaevolent spirits from gym", 210.99, 1, null);
insert into maintenance values ("Terminexx", 2020-05-03, 2020-05-06, "removed raccoons from bedroom", 50.24, 1, 10);
insert into maintenance values ("PlumbCo", 2020-01-10, 2020-01-10, "replaced shattered toilet", 200.87, 2, 6);
insert into maintenance values ("ElectroPro", 2020-02-10, 2020-02-18, "rewired entire living room after The Incident", 1450.69, 2, 8);
insert into maintenance values ("Terminexx", 2020-03-12, 2020-03-12, "fumigated storage sheds for Australian Huntsman spiders", 189.12, 2, null);
insert into maintenance values ("Claude's Repairs", 2020-02-14, 2020-02-16, "repaired shotgun damage to bedroom wall", 300.64, 3, 3);
insert into maintenance values ("Plumbco", 2020-06-20, 2020-06-20, "neutralized sewage geiser from toilet", 310.45, 3, 7);
insert into maintenance values ("ElectroPro", 2020-04-21, 2020-04-22, "fixed flickering lights in kitchen", 230.34, 3, 1);

/*data for parking table*/
insert into parking values (1, 1);
insert into parking values (1, 2);
insert into parking values (1, 3);
insert into parking values (1, 4);
insert into parking values (1, 5);
insert into parking values (1, 6);
insert into parking values (1, 7);
insert into parking values (1, 8);
insert into parking values (1, 9);
insert into parking values (1, 10);
insert into parking values (2, 1);
insert into parking values (2, 2);
insert into parking values (2, 3);
insert into parking values (2, 4);
insert into parking values (2, 5);
insert into parking values (2, 6);
insert into parking values (2, 7);
insert into parking values (2, 8);
insert into parking values (2, 9);
insert into parking values (2, 10);
insert into parking values (3, 1);
insert into parking values (3, 2);
insert into parking values (3, 3);
insert into parking values (3, 4);
insert into parking values (3, 5);
insert into parking values (3, 6);
insert into parking values (3, 7);
insert into parking values (3, 8);
insert into parking values (3, 9);
insert into parking values (3, 10);

/*data for public_spaces table*/
insert into public_spaces values (1, "gym", 210);
insert into public_spaces values (2, "gym", 250);
insert into public_spaces values (3, "gym", 300);

/*data for storage_spaces table*/
insert into storage_spaces values (1, 1);
insert into storage_spaces values (1, 2);
insert into storage_spaces values (1, 3);
insert into storage_spaces values (1, 4);
insert into storage_spaces values (1, 5);
insert into storage_spaces values (1, 6);
insert into storage_spaces values (1, 7);
insert into storage_spaces values (1, 8);
insert into storage_spaces values (1, 9);
insert into storage_spaces values (1, 10);
insert into storage_spaces values (2, 1);
insert into storage_spaces values (2, 2);
insert into storage_spaces values (2, 3);
insert into storage_spaces values (2, 4);
insert into storage_spaces values (2, 5);
insert into storage_spaces values (2, 6);
insert into storage_spaces values (2, 7);
insert into storage_spaces values (2, 8);
insert into storage_spaces values (2, 9);
insert into storage_spaces values (2, 10);
insert into storage_spaces values (3, 1);
insert into storage_spaces values (3, 2);
insert into storage_spaces values (3, 3);
insert into storage_spaces values (3, 4);
insert into storage_spaces values (3, 5);
insert into storage_spaces values (3, 6);
insert into storage_spaces values (3, 7);
insert into storage_spaces values (3, 8);
insert into storage_spaces values (3, 9);
insert into storage_spaces values (3, 10);


